# Generated by Django 4.0.2 on 2023-05-16 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_date', models.DateField(default='2020-12-20')),
                ('aircraft_type', models.CharField(choices=[('A321-200', 'A321-200'), ('A330-200', 'A330-200'), ('A330-300', 'A330-300'), ('777-300ER', '777-300ER'), ('777-300ERSF', '777-300ERSF'), ('777F', '777F'), ('787-9 Dreamliner', '787-9 Dreamliner'), ('787-10 Dreamliner', '787-10 Dreamliner')], default='777-300ER', max_length=20)),
                ('ship_no', models.CharField(choices=[('B16206', 'A321-200 B16206'), ('B16310', 'A330-200 B16310'), ('B16311', 'A330-200 B16311'), ('B16312', 'A330-200 B16312'), ('B16331', 'A330-300 B16331'), ('B16332', 'A330-300 B16332'), ('B16333', 'A330-300 B16333'), ('B16703', '777-300ER B16703'), ('B16705', '777-300ER B16705'), ('B16706', '777-300ER B16706'), ('B16701', '777-300ERSF B16701'), ('B16740', '777-300ERSF B16740'), ('B16781', '777F B16781'), ('B16782', '777F B16782'), ('B16783', '777F B16783'), ('B17881', '787-9 Dreamliner B17881'), ('B17882', '787-9 Dreamliner B17882'), ('B17883', '787-9 Dreamliner B17883'), ('B17801', '787-10 Dreamliner B17801'), ('B17802', '787-10 Dreamliner B17802'), ('B17803', '787-10 Dreamliner B17803')], default='B16703', max_length=20)),
                ('flt_no', models.CharField(max_length=15)),
                ('code_share', models.CharField(choices=[('All Nippon Airways - NH', 'All Nippon Airways - NH'), ('Bangkok Airways - PG', 'Bangkok Airways - PG'), ('Air China - CA', 'Air China - CA'), ('Hainan Airlines - HU', 'Hainan Airlines - HU'), ('Asiana Airlines - OZ', 'Asiana Airlines - OZ'), ('Shandong Airlines - SC', 'Shandong Airlines - SC'), ('Hong Kong Airlines - HX', 'Hong Kong Airlines - HX'), ('United Airlines - UA', 'United Airlines - UA'), ('Singapore Airlines - SQ', 'Singapore Airlines - SQ'), ('Turkish Airlines - TK', 'Turkish Airlines - TK'), ('Air India - AI', 'Air India - AI'), ('Air Canada - AC', 'Air Canada - AC'), ('Shenzhen Airlines - ZH', 'Shenzhen Airlines - ZH'), ('Avianca Airlines - AV', 'Avianca Airlines - AV'), ('Thai Airlines - TG', 'Thai Airlines - TG'), ('Copa Airlines - CM', 'Copa Airlines - CM'), ('Juneyao Airlines - HO', 'Juneyao Airlines - HO'), ('Air New Zealand - NZ', 'Air New Zealand - NZ')], default='All Nippon Airways - NH', max_length=50)),
                ('etd_airport', models.CharField(choices=[('TPE', 'TPE - Taiwan Taoyuan International Airport'), ('HKG', 'HKG - Hong Kong International Airport'), ('LAX', 'LAX - Los Angeles International Airport'), ('SFO', 'SFO - San Francisco International Airport'), ('JFK', 'JFK - John F. Kennedy International Airport'), ('LHR', 'LHR - London Heathrow Airport'), ('SEA', 'SEA - Seattle-Tacoma International Airport'), ('YVR', 'YVR - Vancouver International Airport'), ('YYZ', 'YYZ - Toronto Pearson International Airport'), ('IAH', 'IAH - George Bush Intercontinental Airport'), ('BKK', 'BKK - Suvarnabhumi Airport'), ('NRT', 'NRT - Narita International Airport'), ('ICN', 'ICN - Incheon International Airport'), ('PVG', 'PVG - Shanghai Pudong International Airport'), ('HND', 'HND - Tokyo Haneda Airport'), ('CDG', 'CDG - Charles de Gaulle Airport'), ('AMS', 'AMS - Amsterdam Airport Schiphol'), ('SIN', 'SIN - Singapore Changi Airport'), ('ORD', "ORD - O'Hare International Airport"), ('MUC', 'MUC - Munich Airport'), ('CAN', 'CAN - Guangzhou Baiyun International Airport'), ('SCL', 'SCL - Santiago International Airport'), ('BNE', 'BNE - Brisbane Airport')], default='TPE', max_length=10)),
                ('eta_airport', models.CharField(choices=[('TPE', 'TPE - Taiwan Taoyuan International Airport'), ('HKG', 'HKG - Hong Kong International Airport'), ('LAX', 'LAX - Los Angeles International Airport'), ('SFO', 'SFO - San Francisco International Airport'), ('JFK', 'JFK - John F. Kennedy International Airport'), ('LHR', 'LHR - London Heathrow Airport'), ('SEA', 'SEA - Seattle-Tacoma International Airport'), ('YVR', 'YVR - Vancouver International Airport'), ('YYZ', 'YYZ - Toronto Pearson International Airport'), ('IAH', 'IAH - George Bush Intercontinental Airport'), ('BKK', 'BKK - Suvarnabhumi Airport'), ('NRT', 'NRT - Narita International Airport'), ('ICN', 'ICN - Incheon International Airport'), ('PVG', 'PVG - Shanghai Pudong International Airport'), ('HND', 'HND - Tokyo Haneda Airport'), ('CDG', 'CDG - Charles de Gaulle Airport'), ('AMS', 'AMS - Amsterdam Airport Schiphol'), ('SIN', 'SIN - Singapore Changi Airport'), ('ORD', "ORD - O'Hare International Airport"), ('MUC', 'MUC - Munich Airport'), ('CAN', 'CAN - Guangzhou Baiyun International Airport'), ('SCL', 'SCL - Santiago International Airport'), ('BNE', 'BNE - Brisbane Airport')], default='TPE', max_length=10)),
                ('etd_utc', models.CharField(choices=[('+1', 'UTC+1'), ('+2', 'UTC+2'), ('+3', 'UTC+3'), ('+4', 'UTC+4'), ('+5', 'UTC+5'), ('+6', 'UTC+6'), ('+7', 'UTC+7'), ('+8', 'UTC+8'), ('+9', 'UTC+9'), ('+10', 'UTC+10'), ('+11', 'UTC+11'), ('+12', 'UTC+12'), ('-1', 'UTC-1'), ('-2', 'UTC-2'), ('-3', 'UTC-3'), ('-4', 'UTC-4'), ('-5', 'UTC-5'), ('-6', 'UTC-6'), ('-7', 'UTC-7'), ('-8', 'UTC-8'), ('-9', 'UTC-9'), ('-10', 'UTC-10'), ('-11', 'UTC-11'), ('-12', 'UTC-12')], default='UTC+8', max_length=10)),
                ('eta_utc', models.CharField(choices=[('+1', 'UTC+1'), ('+2', 'UTC+2'), ('+3', 'UTC+3'), ('+4', 'UTC+4'), ('+5', 'UTC+5'), ('+6', 'UTC+6'), ('+7', 'UTC+7'), ('+8', 'UTC+8'), ('+9', 'UTC+9'), ('+10', 'UTC+10'), ('+11', 'UTC+11'), ('+12', 'UTC+12'), ('-1', 'UTC-1'), ('-2', 'UTC-2'), ('-3', 'UTC-3'), ('-4', 'UTC-4'), ('-5', 'UTC-5'), ('-6', 'UTC-6'), ('-7', 'UTC-7'), ('-8', 'UTC-8'), ('-9', 'UTC-9'), ('-10', 'UTC-10'), ('-11', 'UTC-11'), ('-12', 'UTC-12')], default='UTC+8', max_length=10)),
                ('etd', models.DateTimeField()),
                ('schedule_hr', models.DurationField(default='0:00:00')),
                ('fdp_hr', models.DurationField(default='0:00:00')),
                ('RL_PL_SB', models.IntegerField(default=0)),
                ('PE', models.IntegerField(default=0)),
                ('EY', models.IntegerField(default=0)),
                ('RL_PL_SB_booked', models.IntegerField(default=0)),
                ('PE_booked', models.IntegerField(default=0)),
                ('EY_booked', models.IntegerField(default=0)),
                ('CHD', models.IntegerField(default=0)),
                ('INF', models.IntegerField(default=0)),
                ('crew_assigned', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
