# Generated by Django 4.0.2 on 2023-05-16 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0002_flight_crew_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='crew_members',
        ),
    ]
