# Generated by Django 4.0.2 on 2023-05-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0003_remove_flight_crew_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='crew_members',
            field=models.IntegerField(default=0),
        ),
    ]
