# Generated by Django 4.0.2 on 2023-05-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0004_flight_crew_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
