# Generated by Django 4.0.2 on 2023-05-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0005_flight_eta'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airplane',
            field=models.CharField(choices=[('Boeing', 'Boeing'), ('Airbus', 'Airbus')], default='Boeing', max_length=20),
        ),
    ]
