# Generated by Django 4.0.2 on 2023-05-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0006_flight_airplane'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFlightsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='fdp_hr',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='schedule_hr',
        ),
        migrations.AddField(
            model_name='flight',
            name='fdp_hr_h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='fdp_hr_m',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_id',
            field=models.CharField(default='A123456789', max_length=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='schedule_hr_h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='schedule_hr_m',
            field=models.IntegerField(default=0),
        ),
    ]
