# Generated by Django 4.0.2 on 2023-05-17 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0007_newflightsform_remove_flight_fdp_hr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewFlightsForm',
        ),
    ]
