# Generated by Django 4.0.2 on 2023-05-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0008_delete_newflightsform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='etd',
            new_name='etd_date',
        ),
    ]
