# Generated by Django 4.0.2 on 2023-05-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0009_rename_etd_flight_etd_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='etd_date',
            new_name='etd',
        ),
    ]
