# Generated by Django 4.0.2 on 2023-05-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0010_rename_etd_date_flight_etd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='etd',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_id',
            field=models.CharField(default='FLID202500', max_length=20, unique=True),
        ),
    ]
