# Generated by Django 4.0.2 on 2023-05-14 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('id_number', models.CharField(default='A123456789', max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=20)),
                ('birth_date', models.DateField(default='1993-12-20')),
                ('user_type', models.CharField(choices=[('Pessanger', 'Pessanger'), ('Crew', 'Crew'), ('Pilot', 'Pilot'), ('Office', 'Office')], default='Pessanger', max_length=20)),
                ('miles', models.IntegerField(default=0)),
                ('level', models.CharField(choices=[('Green', 'Green'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Diamond', 'Diamond')], default='Green', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
