# Generated by Django 4.0.2 on 2023-05-15 09:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('id_number', models.CharField(default='A123456789', max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=20)),
                ('birth_date', models.DateField(default='1993-12-20')),
                ('user_type', models.CharField(choices=[('Crew - TA', 'Crew - TA'), ('Crew - CA', 'Crew - CA'), ('Crew - AP', 'Crew - AP'), ('Crew - DP', 'Crew - DP'), ('Crew - CP', 'Crew - CP'), ('Crew - IC', 'Crew - IC'), ('Pilot', 'Pilot'), ('Office - DC', 'Office - DC'), ('Office - FlightM', 'Office - FlightM')], default='Crew - TA', max_length=20)),
                ('angel_class', models.CharField(choices=[('2023A', '2023A'), ('2023B', '2023B'), ('2023C', '2023C'), ('2023D', '2023D'), ('2023E', '2023E')], default='2023A', max_length=20)),
                ('times', models.IntegerField(default=0)),
                ('employee_id', models.CharField(default='8BF3A64E', max_length=8, unique=True, validators=[django.core.validators.MaxLengthValidator(8)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
