# Generated by Django 4.0.2 on 2023-05-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_staffuserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuserprofile',
            name='employee_id',
            field=models.CharField(default='233YDZ5C', max_length=8),
        ),
        migrations.AlterField(
            model_name='staffuserprofile',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
