# Generated by Django 4.0.2 on 2023-05-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_staffuserprofile_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuserprofile',
            name='employee_id',
            field=models.CharField(default='YJ7TCPZN', max_length=8),
        ),
    ]
