# Generated by Django 4.0.2 on 2023-05-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_staffuserprofile_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuserprofile',
            name='employee_id',
            field=models.CharField(default='BOXZRZ3R', max_length=8),
        ),
    ]
