# Generated by Django 4.0.2 on 2023-05-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_alter_staffuserprofile_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuserprofile',
            name='employee_id',
            field=models.CharField(default='O75XCLKA', max_length=8),
        ),
    ]
